import Head from 'next/head'

import Header from '@/components/header'
// import Content from '@/components/content'
import Footer from '@/components/footer'

//TODO: define 'Layout Component'
//? as a wrapper (frame) -- for every routing pages (re-used component)
//! use prop: {children} as page-router -- (access all react node) to make content-dynamic
// -- use prop: {metaTitle} to make title-dynamic
export default function Layout({ children, metaTitle, metaDescription }) {
  return (
    <div>
      <Head>
        <title>Create Next App - {metaTitle}</title>
        <meta
          name="description"
          content={metaDescription || 'Generated by create next app'} />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {children}
      <Footer />

    </div>
  )
}