import Head from 'next/head';

import Header from '@/components/header/index';
// import Content from '@/components/content'
import Footer from '@/components/footer';

//! -------- Tugas H5: define 'Layout Component' as wrapper (frame) --------
//? as a wrapper (frame) -- for every routing pages (re-used component)
//! use prop: {children} as page-router -- (access all react node) to make content-dynamic
// -- use prop: {metaTitle} to make title-dynamic
export default function Layout({ children, metaTitle, metaDescription }) {
  return (
    <div>
      <Head>
        {/* add prop: metaTitle */}
        <title>{`Create Next App - ${metaTitle}`}</title>
        {/* if error exist, use template literals (literal string) as below:  */}
        {/* <title>{`Create Next App - ${metaTitle}`}</title> */}
        <meta
          name="description"
          // add prop: metaDescription -- to improve SEO
          //? if at routing pages - have no 'metaDescription' -- use desc:'Generated ...'
          content={metaDescription || 'Generated by create next app'} />

        <meta
          name="viewport"
          content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {children}
      <Footer />

    </div>
  )
}