import Head from 'next/head'

import Header from '@/components/header'
// import Content from '@/components/content'
import Footer from '@/components/footer'

//! use {children} as page-router -- (access all react node) to make content-dynamic
export default function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>Create Next App - Dynamic Route</title>
        <meta
          name="description"
          content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {children}
      <Footer />

    </div>
  )
}